name: Daily Summary Report

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: {}

jobs:
  summary:
    runs-on: ubuntu-latest

    permissions: # เพิ่มส่วนนี้เพื่ออนุญาตให้ Workflow สามารถ Push ไฟล์กลับไปยัง Repository ได้
      contents: write # อนุญาตให้เขียนลงใน Repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib requests pytz

      - name: Run Daily Summary and Generate Graph
        run: python summary_report.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}

      - name: Commit and push generated graph
        uses: EndBug/add-and-commit@v9 # ใช้ Action สำเร็จรูปสำหรับการ Commit และ Push
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: Update daily summary graph"
          add: "chaop_summary.png" # ระบุไฟล์ที่ต้องการเพิ่มและ Commit
