name: Water Level Scraper

on:
  schedule:
    - cron: '45 0 * * *' # รันทุกวันเวลา 00:45 UTC (07:45 น. ICT)
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # เพิ่มสิทธิ์ write เพื่อให้ commit ได้
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ดึงประวัติทั้งหมด เพื่อป้องกันปัญหา Merge
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        run: python scraper.py
      - name: Commit and push historical_log.csv
        uses: EndBug/add-and-commit@v9 # ใช้ Action สำเร็จรูปสำหรับการ Commit และ Push
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: Update historical_log.csv" # ข้อความ Commit
          add: "historical_log.csv"
          push: true
          # pathspec_error_handling: ignore # อาจเพิ่มอันนี้ถ้า commit แล้วไม่มีการเปลี่ยนแปลง
