name: Water Level Scraper

on:
  workflow_dispatch:
  schedule:
    # ตรวจสอบทุก 5 นาที (ยังคงเหมือนเดิม)
    - cron: '*/30 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # เพิ่ม Step นี้: ลบ last_data.txt ก่อนรัน เพื่อให้แน่ใจว่าค่า 'last' เป็นว่าง
      - name: ลบ last_data.txt ก่อนรัน
        run: |
          if [ -f last_data.txt ]; then
            rm last_data.txt
          fi

      - name: Run scraper script
        env:
          MAKE_COM_WEBHOOK_URL: ${{ secrets.MAKE_COM_WEBHOOK_URL }}
          # เพิ่มตัวแปรนี้เพื่อบังคับให้ส่งข้อมูลไป Make.com เสมอในการทดสอบ
          FORCE_SEND: 'true'
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          # เพิ่ม historical_log.csv เข้าไปใน git ด้วย
          git add last_data.txt historical_log.csv
          if ! git diff --staged --quiet; then
            git commit -m "Update water data and historical log"
            git push
          else
            echo "No changes to commit."
          fi
