# .github/workflows/river_alert.yml
name: Inburi Bridge Alert

on:
  schedule:
    # รันทุก 15 นาที (UTC)
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest

    env:
      # บรรทัดนี้จะเปลี่ยนไปใช้ Secret ใหม่สำหรับ Inburi Bridge
      MAKE_COM_WEBHOOK_URL:  ${{ secrets.INBURI_WEBHOOK_URL }} # นี่คือการเปลี่ยนแปลง
      NOTIFICATION_THRESHOLD_M:  ${{ secrets.NOTIFICATION_THRESHOLD_M }}
      FORCE_SEND: 'true' # ยังคงบังคับส่งเพื่อการทดสอบ

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: ลบ inburi_bridge_data.json ก่อนรัน
        run: |
          if [ -f inburi_bridge_data.json ]; then
            rm inburi_bridge_data.json
          fi

      - name: Run alert script
        run: python inburi_bridge_alert.py
