name: Weather Alert

on:
  schedule:
    - cron: '45 0 * * *' # รันทุกวันเวลา 00:45 UTC (07:45 น. ICT)
  workflow_dispatch: {}

jobs:
  check_weather:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ดึงประวัติทั้งหมด
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # ใช้ 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Weather Forecaster Script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
        run: python weather_forecaster.py
      - name: Commit and push weather_log.csv
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: Update weather_log.csv"
          add: "weather_log.csv"
          pull: true # *** เพิ่มบรรทัดนี้ ***
          push: true
